# Generated by Django 2.0.6 on 2018-06-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datatable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.IntegerField(max_length=10)),
                ('other', models.IntegerField(max_length=10)),
            ],
        ),
    ]
