# Generated by Django 2.0.6 on 2018-06-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='food',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='other',
            field=models.IntegerField(),
        ),
    ]
