# Generated by Django 2.0.6 on 2018-07-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_auto_20180629_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='datatable1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.IntegerField()),
                ('trip', models.IntegerField()),
                ('shopping', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='datatable',
        ),
    ]
