# Generated by Django 2.0.6 on 2018-07-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_auto_20180703_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='datatable2',
            fields=[
                ('roomid', models.IntegerField(primary_key=True, serialize=False)),
                ('food', models.IntegerField()),
                ('trip', models.IntegerField()),
                ('shopping', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='datatable1',
        ),
    ]
